In [1]:
import numpy as np
from matplotlib import pyplot as plt
from numpy import random as rnd
import warnings,datetime,os,calendar,csv,time

from scipy.signal import find_peaks
import networkx as nx

import tensorflow as tf
import pandas as pd
import seaborn as sns

from keras.models import Model,Sequential
from keras.layers import Dense,LSTM,Conv2D,Dropout,BatchNormalization,Input,Concatenate,Add,Activation,MaxPooling2D,AveragePooling2D
import keras.backend as K

from sklearn import preprocessing as pp

from sklearn.cluster import KMeans,MeanShift
from sklearn.dummy import DummyClassifier,DummyRegressor
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,RandomForestClassifier,RandomForestRegressor
from sklearn.linear_model import BayesianRidge,Lasso,LinearRegression,SGDClassifier,SGDRegressor
from sklearn.mixture import BayesianGaussianMixture,GaussianMixture
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor,RadiusNeighborsClassifier,RadiusNeighborsRegressor,NearestNeighbors
from sklearn.manifold import Isomap
from sklearn.model_selection import KFold,StratifiedKFold,train_test_split
from sklearn.svm import LinearSVC,LinearSVR
from sklearn.neural_network import BernoulliRBM,MLPClassifier,MLPRegressor
from sklearn.decomposition import FactorAnalysis,KernelPCA,PCA,MiniBatchSparsePCA,FastICA
from sklearn.preprocessing import CategoricalEncoder,KBinsDiscretizer,LabelEncoder,MinMaxScaler,OneHotEncoder,StandardScaler

from xgboost import XGBClassifier,XGBRegressor
import gym

import pickle,h5py,json
import urllib
from bs4 import BeautifulSoup

import pygame
from pygame.locals import *

warnings.filterwarnings('ignore')
sns.set()
plt.xkcd()

C:\Users\Jan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html


In [138]:
BATCHSIZE = 3
NUM_EPOCHS = 50
LR = 0.1

NUM_NODES = 3

In [145]:
tf.reset_default_graph()

sample = tf.placeholder(dtype=tf.float32,shape=[None,NUM_NODES])
C = tf.Variable(tf.random_normal([NUM_NODES,NUM_NODES])) 

act = tf.nn.relu(tf.matmul(sample,C))
E_t = tf.norm(sample)+tf.norm(act)-2*tf.tensordot(sample,act,2)
reg = tf.abs(tf.norm(tf.linalg.diag_part(C)))

loss = tf.add(E_t,reg)

optimize = tf.train.AdamOptimizer(learning_rate=LR).minimize(loss)

In [146]:
D = np.array([[1,0,0],[0,1,0],[0,0,1]]*30)

In [147]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

epoch = 0
while epoch < NUM_EPOCHS:
    DD = D[rnd.permutation(np.arange(D.shape[0]))]
    
    for k in range(DD.shape[0]-BATCHSIZE):
        d = DD[k:k+BATCHSIZE,:]
        free_energy,_ = sess.run([E_t,optimize],feed_dict={
            sample:d.reshape(BATCHSIZE,NUM_NODES)
        })
        print(free_energy)
        print(sess.run(C))
    
    epoch += 1

print(sess.run(C))
sess.close()

2.5687754
[[-0.08697359  0.33449054  0.61507076]
 [-0.77856576 -0.2660586  -0.07324356]
 [-1.4869921  -0.6970488   1.1151998 ]]
0.8184147
[[ 0.00678483  0.24159417  0.52057815]
 [-0.77856576 -0.16714111 -0.07324356]
 [-1.4869921  -0.6970488   1.0635473 ]]
0.9157121
[[ 0.07359402  0.14683987  0.4236359 ]
 [-0.77856576 -0.0718345  -0.07324356]
 [-1.4869921  -0.6970488   1.0386397 ]]
0.58173203
[[ 0.1533088   0.05430038  0.3259836 ]
 [-0.77856576  0.01498898 -0.07324356]
 [-1.4869921  -0.6970488   1.0274615 ]]
0.21328902
[[ 0.2395342  -0.03033598  0.22912252]
 [-0.77856576  0.08638152 -0.07324356]
 [-1.4869921  -0.6970488   1.02443   ]]
-1.3585386
[[ 0.32414904 -0.1032815   0.14083499]
 [-0.77856576  0.13632648 -0.07324356]
 [-1.4869921  -0.6970488   1.0676644 ]]
-2.8246865
[[ 0.39581907 -0.16698526  0.06373294]
 [-0.77856576  0.16387402 -0.07324356]
 [-1.4869921  -0.6970488   1.1304231 ]]
-1.5103526
[[ 0.45652992 -0.22314398 -0.00423719]
 [-0.77856576  0.21778882 -0.07324356]
 [-1.486992

-15.320574
[[ 4.1840663  -0.74542993 -0.63637096]
 [-0.77856576  3.8737516  -0.07324356]
 [-1.4869921  -0.6970488   4.5599093 ]]
-15.679322
[[ 4.2741284  -0.7455342  -0.63649714]
 [-0.77856576  3.9548788  -0.07324356]
 [-1.4869921  -0.6970488   4.558209  ]]
-16.050827
[[ 4.368846   -0.74562865 -0.6366115 ]
 [-0.77856576  4.034591   -0.07324356]
 [-1.4869921  -0.6970488   4.5520854 ]]
-16.433388
[[ 4.4676156  -0.7457143  -0.6367152 ]
 [-0.77856576  4.1130247  -0.07324356]
 [-1.4869921  -0.6970488   4.541998  ]]
-16.929935
[[ 4.5621758  -0.7457919  -0.6368091 ]
 [-0.77856576  4.190328   -0.07324356]
 [-1.4869921  -0.6970488   4.5389047 ]]
-16.642532
[[ 4.6439743  -0.74586225 -0.6368942 ]
 [-0.77856576  4.2753196  -0.07324356]
 [-1.4869921  -0.6970488   4.5421505 ]]
-16.891266
[[ 4.714173   -0.74592596 -0.63697135]
 [-0.77856576  4.366954   -0.07324356]
 [-1.4869921  -0.6970488   4.55126   ]]
-17.394684
[[ 4.7827945  -0.74598366 -0.6370412 ]
 [-0.77856576  4.4643927  -0.07324356]
 [-1.486

-32.000328
[[ 7.9010572  -0.74653417 -0.6377073 ]
 [-0.77856576  7.8277564  -0.07324356]
 [-1.4869921  -0.6970488   8.158715  ]]
-32.1446
[[ 7.973894   -0.74653435 -0.6377075 ]
 [-0.77856576  7.8727956  -0.07324356]
 [-1.4869921  -0.6970488   8.216654  ]]
-32.84421
[[ 8.035729   -0.74653447 -0.63770765]
 [-0.77856576  7.9196415  -0.07324356]
 [-1.4869921  -0.6970488   8.283939  ]]
-32.583668
[[ 8.087615   -0.7465346  -0.6377078 ]
 [-0.77856576  7.977792   -0.07324356]
 [-1.4869921  -0.6970488   8.350277  ]]
-33.000317
[[ 8.140306   -0.7465347  -0.63770795]
 [-0.77856576  8.036411   -0.07324356]
 [-1.4869921  -0.6970488   8.415785  ]]
-33.25176
[[ 8.193744   -0.7465348  -0.63770807]
 [-0.77856576  8.095466   -0.07324356]
 [-1.4869921  -0.6970488   8.480553  ]]
-33.50385
[[ 8.247872   -0.74653494 -0.6377082 ]
 [-0.77856576  8.154925   -0.07324356]
 [-1.4869921  -0.6970488   8.544662  ]]
-33.75657
[[ 8.302642   -0.746535   -0.6377083 ]
 [-0.77856576  8.214762   -0.07324356]
 [-1.4869921  

[[14.529096   -0.7465356  -0.6377091 ]
 [-0.77856576 13.520815   -0.07324356]
 [-1.4869921  -0.6970488  13.745331  ]]
-56.292793
[[14.552249   -0.7465356  -0.6377091 ]
 [-0.77856576 13.595063   -0.07324356]
 [-1.4869921  -0.6970488  13.823044  ]]
-56.938934
[[14.569108   -0.7465356  -0.6377091 ]
 [-0.77856576 13.668018   -0.07324356]
 [-1.4869921  -0.6970488  13.908413  ]]
-57.62835
[[14.580295   -0.7465356  -0.6377091 ]
 [-0.77856576 13.729898   -0.07324356]
 [-1.4869921  -0.6970488  14.009486  ]]
-58.86737
[[14.595828   -0.7465356  -0.6377091 ]
 [-0.77856576 13.781782   -0.07324356]
 [-1.4869921  -0.6970488  14.1157    ]]
-59.19299
[[14.615316   -0.7465356  -0.6377091 ]
 [-0.77856576 13.824644   -0.07324356]
 [-1.4869921  -0.6970488  14.22645   ]]
-60.090153
[[14.647853   -0.7465356  -0.6377091 ]
 [-0.77856576 13.859366   -0.07324356]
 [-1.4869921  -0.6970488  14.332082  ]]
-59.20691
[[14.682668   -0.7465356  -0.6377091 ]
 [-0.77856576 13.896829   -0.07324356]
 [-1.4869921  -0.697048

-74.444855
[[17.745646   -0.7465356  -0.6377091 ]
 [-0.77856576 18.254871   -0.07324356]
 [-1.4869921  -0.6970488  17.719126  ]]
-74.68924
[[17.780094   -0.7465356  -0.6377091 ]
 [-0.77856576 18.33459    -0.07324356]
 [-1.4869921  -0.6970488  17.777325  ]]
-74.9341
[[17.817032   -0.7465356  -0.6377091 ]
 [-0.77856576 18.4119     -0.07324356]
 [-1.4869921  -0.6970488  17.83575   ]]
-76.02583
[[17.846397   -0.7465356  -0.6377091 ]
 [-0.77856576 18.496212   -0.07324356]
 [-1.4869921  -0.6970488  17.89443   ]]
-77.20884
[[17.868935   -0.7465356  -0.6377091 ]
 [-0.77856576 18.595592   -0.07324356]
 [-1.4869921  -0.6970488  17.943325  ]]
-76.59367
[[17.895248   -0.7465356  -0.6377091 ]
 [-0.77856576 18.699533   -0.07324356]
 [-1.4869921  -0.6970488  17.983397  ]]
-75.78132
[[17.934675   -0.7465356  -0.6377091 ]
 [-0.77856576 18.798544   -0.07324356]
 [-1.4869921  -0.6970488  18.015512  ]]
-74.812225
[[17.995045   -0.7465356  -0.6377091 ]
 [-0.77856576 18.883879   -0.07324356]
 [-1.4869921  -

 [-1.4869921  -0.6970488  24.733665  ]]
-101.41354
[[24.102684   -0.7465356  -0.6377091 ]
 [-0.77856576 24.26349    -0.07324356]
 [-1.4869921  -0.6970488  24.809952  ]]
-102.59836
[[24.161636   -0.7465356  -0.6377091 ]
 [-0.77856576 24.304438   -0.07324356]
 [-1.4869921  -0.6970488  24.884432  ]]
-103.64569
[[24.210817   -0.7465356  -0.6377091 ]
 [-0.77856576 24.347076   -0.07324356]
 [-1.4869921  -0.6970488  24.966942  ]]
-103.74543
[[24.261097   -0.7465356  -0.6377091 ]
 [-0.77856576 24.381649   -0.07324356]
 [-1.4869921  -0.6970488  25.056612  ]]
-102.939865
[[24.322035   -0.7465356  -0.6377091 ]
 [-0.77856576 24.408955   -0.07324356]
 [-1.4869921  -0.6970488  25.143093  ]]
-102.196754
[[24.392439   -0.7465356  -0.6377091 ]
 [-0.77856576 24.439262   -0.07324356]
 [-1.4869921  -0.6970488  25.216925  ]]
-103.6082
[[24.46178    -0.7465356  -0.6377091 ]
 [-0.77856576 24.472334   -0.07324356]
 [-1.4869921  -0.6970488  25.289143  ]]
-103.85638
[[24.530169   -0.7465356  -0.6377091 ]
 [-0.7

-120.18535
[[28.995024   -0.7465356  -0.6377091 ]
 [-0.77856576 28.470226   -0.07324356]
 [-1.4869921  -0.6970488  30.210724  ]]
-120.52217
[[29.069834   -0.7465356  -0.6377091 ]
 [-0.77856576 28.5577     -0.07324356]
 [-1.4869921  -0.6970488  30.221994  ]]
-123.23273
[[29.143085   -0.7465356  -0.6377091 ]
 [-0.77856576 28.642427   -0.07324356]
 [-1.4869921  -0.6970488  30.237902  ]]
-122.76539
[[29.20514    -0.7465356  -0.6377091 ]
 [-0.77856576 28.734165   -0.07324356]
 [-1.4869921  -0.6970488  30.257977  ]]
-123.72983
[[29.266907   -0.7465356  -0.6377091 ]
 [-0.77856576 28.822712   -0.07324356]
 [-1.4869921  -0.6970488  30.281845  ]]
-122.54437
[[29.337967   -0.7465356  -0.6377091 ]
 [-0.77856576 28.908337   -0.07324356]
 [-1.4869921  -0.6970488  30.299116  ]]
-123.480896
[[29.4267     -0.7465356  -0.6377091 ]
 [-0.77856576 28.981636   -0.07324356]
 [-1.4869921  -0.6970488  30.310444  ]]
-125.11182
[[29.521969   -0.7465356  -0.6377091 ]
 [-0.77856576 29.043825   -0.07324356]
 [-1.48

-162.76625
[[37.730064   -0.7465356  -0.6377091 ]
 [-0.77856576 36.672874   -0.07324356]
 [-1.4869921  -0.6970488  38.63012   ]]
-161.85481
[[37.760902   -0.7465356  -0.6377091 ]
 [-0.77856576 36.725597   -0.07324356]
 [-1.4869921  -0.6970488  38.724575  ]]
-160.79584
[[37.80436    -0.7465356  -0.6377091 ]
 [-0.77856576 36.769184   -0.07324356]
 [-1.4869921  -0.6970488  38.815468  ]]
-158.13684
[[37.858997   -0.7465356  -0.6377091 ]
 [-0.77856576 36.814507   -0.07324356]
 [-1.4869921  -0.6970488  38.89313   ]]
-156.8707
[[37.91397    -0.7465356  -0.6377091 ]
 [-0.77856576 36.871174   -0.07324356]
 [-1.4869921  -0.6970488  38.958874  ]]
-158.57999
[[37.9595     -0.7465356  -0.6377091 ]
 [-0.77856576 36.938087   -0.07324356]
 [-1.4869921  -0.6970488  39.023834  ]]
-161.83057
[[37.996517   -0.7465356  -0.6377091 ]
 [-0.77856576 37.00447    -0.07324356]
 [-1.4869921  -0.6970488  39.09805   ]]
-162.13605
[[38.025867   -0.7465356  -0.6377091 ]
 [-0.77856576 37.07038    -0.07324356]
 [-1.4869

-180.56796
[[43.05967    -0.7465356  -0.6377091 ]
 [-0.77856576 42.254833   -0.07324356]
 [-1.4869921  -0.6970488  42.180893  ]]
-179.646
[[43.149364   -0.7465356  -0.6377091 ]
 [-0.77856576 42.300877   -0.07324356]
 [-1.4869921  -0.6970488  42.222015  ]]
-179.89726
[[43.235817   -0.7465356  -0.6377091 ]
 [-0.77856576 42.34823    -0.07324356]
 [-1.4869921  -0.6970488  42.26536   ]]
-178.8901
[[43.309677   -0.7465356  -0.6377091 ]
 [-0.77856576 42.406452   -0.07324356]
 [-1.4869921  -0.6970488  42.310688  ]]
-180.53784
[[43.38187    -0.7465356  -0.6377091 ]
 [-0.77856576 42.474483   -0.07324356]
 [-1.4869921  -0.6970488  42.34728   ]]
-182.125
[[43.46216    -0.7465356  -0.6377091 ]
 [-0.77856576 42.541656   -0.07324356]
 [-1.4869921  -0.6970488  42.376     ]]
-182.21176
[[43.549686   -0.7465356  -0.6377091 ]
 [-0.77856576 42.5982     -0.07324356]
 [-1.4869921  -0.6970488  42.40824   ]]
-182.50612
[[43.6437     -0.7465356  -0.6377091 ]
 [-0.77856576 42.645172   -0.07324356]
 [-1.4869921 

-209.65538
[[47.85467    -0.7465356  -0.6377091 ]
 [-0.77856576 48.535442   -0.07324356]
 [-1.4869921  -0.6970488  50.145317  ]]
-207.69489
[[47.87188    -0.7465356  -0.6377091 ]
 [-0.77856576 48.621544   -0.07324356]
 [-1.4869921  -0.6970488  50.22037   ]]
-206.97333
[[47.893494   -0.7465356  -0.6377091 ]
 [-0.77856576 48.704994   -0.07324356]
 [-1.4869921  -0.6970488  50.29378   ]]
-204.9813
[[47.91904    -0.7465356  -0.6377091 ]
 [-0.77856576 48.795704   -0.07324356]
 [-1.4869921  -0.6970488  50.355656  ]]
-207.47969
[[47.94818    -0.7465356  -0.6377091 ]
 [-0.77856576 48.883293   -0.07324356]
 [-1.4869921  -0.6970488  50.417206  ]]
-209.07242
[[47.970455   -0.7465356  -0.6377091 ]
 [-0.77856576 48.97783    -0.07324356]
 [-1.4869921  -0.6970488  50.47849   ]]
-209.42899
[[47.98654    -0.7465356  -0.6377091 ]
 [-0.77856576 49.078587   -0.07324356]
 [-1.4869921  -0.6970488  50.53954   ]]
-206.17453
[[48.007156   -0.7465356  -0.6377091 ]
 [-0.77856576 49.184776   -0.07324356]
 [-1.4869

-225.45369
[[52.95171    -0.7465356  -0.6377091 ]
 [-0.77856576 52.810528   -0.07324356]
 [-1.4869921  -0.6970488  54.253666  ]]
-223.66058
[[53.009182   -0.7465356  -0.6377091 ]
 [-0.77856576 52.897858   -0.07324356]
 [-1.4869921  -0.6970488  54.28529   ]]
-224.19165
[[53.066765   -0.7465356  -0.6377091 ]
 [-0.77856576 52.992176   -0.07324356]
 [-1.4869921  -0.6970488  54.309597  ]]
-226.41031
[[53.124485   -0.7465356  -0.6377091 ]
 [-0.77856576 53.08306    -0.07324356]
 [-1.4869921  -0.6970488  54.337368  ]]
-226.66167
[[53.182335   -0.7465356  -0.6377091 ]
 [-0.77856576 53.170853   -0.07324356]
 [-1.4869921  -0.6970488  54.368263  ]]
-226.91318
[[53.2403     -0.7465356  -0.6377091 ]
 [-0.77856576 53.25586    -0.07324356]
 [-1.4869921  -0.6970488  54.40198   ]]
-227.16486
[[53.298374   -0.7465356  -0.6377091 ]
 [-0.77856576 53.338356   -0.07324356]
 [-1.4869921  -0.6970488  54.438248  ]]
-227.41673
[[53.356552   -0.7465356  -0.6377091 ]
 [-0.77856576 53.418594   -0.07324356]
 [-1.486

-250.82645
[[59.31827    -0.7465356  -0.6377091 ]
 [-0.77856576 60.30554    -0.07324356]
 [-1.4869921  -0.6970488  59.085648  ]]
-251.10422
[[59.402287   -0.7465356  -0.6377091 ]
 [-0.77856576 60.352898   -0.07324356]
 [-1.4869921  -0.6970488  59.13053   ]]
-251.40704
[[59.493362   -0.7465356  -0.6377091 ]
 [-0.77856576 60.391544   -0.07324356]
 [-1.4869921  -0.6970488  59.17711   ]]
-251.28244
[[59.58117    -0.7465356  -0.6377091 ]
 [-0.77856576 60.42234    -0.07324356]
 [-1.4869921  -0.6970488  59.235416  ]]
-251.57321
[[59.66603    -0.7465356  -0.6377091 ]
 [-0.77856576 60.446064   -0.07324356]
 [-1.4869921  -0.6970488  59.304245  ]]
-251.37546
[[59.738503   -0.7465356  -0.6377091 ]
 [-0.77856576 60.46342    -0.07324356]
 [-1.4869921  -0.6970488  59.392445  ]]
-253.27182
[[59.799812   -0.7465356  -0.6377091 ]
 [-0.77856576 60.484776   -0.07324356]
 [-1.4869921  -0.6970488  59.48807   ]]
-254.99277
[[59.851067   -0.7465356  -0.6377091 ]
 [-0.77856576 60.519466   -0.07324356]
 [-1.486

-271.86932
[[63.50755    -0.7465356  -0.6377091 ]
 [-0.77856576 64.432304   -0.07324356]
 [-1.4869921  -0.6970488  64.034676  ]]
-271.37854
[[63.5632     -0.7465356  -0.6377091 ]
 [-0.77856576 64.49299    -0.07324356]
 [-1.4869921  -0.6970488  64.095764  ]]
-272.19537
[[63.6192     -0.7465356  -0.6377091 ]
 [-0.77856576 64.56314    -0.07324356]
 [-1.4869921  -0.6970488  64.14662   ]]
-271.13168
[[63.685215   -0.7465356  -0.6377091 ]
 [-0.77856576 64.63208    -0.07324356]
 [-1.4869921  -0.6970488  64.18826   ]]
-272.1339
[[63.750534   -0.7465356  -0.6377091 ]
 [-0.77856576 64.69994    -0.07324356]
 [-1.4869921  -0.6970488  64.23184   ]]
-271.72076
[[63.81522    -0.7465356  -0.6377091 ]
 [-0.77856576 64.757034   -0.07324356]
 [-1.4869921  -0.6970488  64.287315  ]]
-273.31055
[[63.869526   -0.7465356  -0.6377091 ]
 [-0.77856576 64.81425    -0.07324356]
 [-1.4869921  -0.6970488  64.35349   ]]
-273.58026
[[63.914482   -0.7465356  -0.6377091 ]
 [-0.77856576 64.87157    -0.07324356]
 [-1.4869

 [-1.4869921e+00 -6.9704878e-01  7.3333626e+01]]
-312.83167
[[ 7.2346085e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.4519928e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  7.3399879e+01]]
-314.7185
[[ 7.2376228e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.4601608e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  7.3465698e+01]]
-315.0445
[[ 7.2399376e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.4690392e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  7.3531136e+01]]
-313.74078
[[ 7.2416229e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.4775993e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  7.3606422e+01]]
-312.41644
[[ 7.2427414e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.4849083e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  7.3700500e+01]]
-311.00253
[[ 7.2443542e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.4910904e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  7.3801361e+01]]
-311.31186
[[ 7.2

-339.01663
[[ 7.9201683e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.9082542e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.1354073e+01]]
-339.1775
[[ 7.9265076e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.9096535e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.1454773e+01]]
-339.43015
[[ 7.9328102e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.9115044e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.1551285e+01]]
-339.37854
[[ 7.9380875e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.9147430e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.1644012e+01]]
-339.9353
[[ 7.9434341e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.9182503e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.1733345e+01]]
-340.18784
[[ 7.9488441e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  7.9220001e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.1819618e+01]]
-340.824
[[ 7.9552971e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856

-360.14438
[[ 8.4486488e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.5062973e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.4327171e+01]]
-359.44446
[[ 8.4549416e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.5149979e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.4351860e+01]]
-359.69272
[[ 8.4611954e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.5233986e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.4380264e+01]]
-360.82605
[[ 8.4664268e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.5324776e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.4412033e+01]]
-362.42975
[[ 8.4707375e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.5431007e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.4436455e+01]]
-361.466
[[ 8.4742180e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.5541710e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.4464653e+01]]
-360.28842
[[ 8.4769516e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.78

-376.1449
[[ 8.6933838e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.7919998e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.8970139e+01]]
-376.49164
[[ 8.6946335e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.7992249e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.9062668e+01]]
-376.85757
[[ 8.6953583e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.8063072e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.9161995e+01]]
-377.24078
[[ 8.6956108e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.8132607e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.9267418e+01]]
-376.02505
[[ 8.6954376e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.8210541e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.9368294e+01]]
-374.5965
[[ 8.6958878e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  8.8286446e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  8.9465057e+01]]
-374.84784
[[ 8.6968987e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.78

-388.40128
[[ 9.1598389e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.1494293e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.3688538e+01]]
-388.76093
[[ 9.1643654e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.1595139e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.3718193e+01]]
-389.1913
[[ 9.1680420e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.1710770e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.3740669e+01]]
-392.5641
[[ 9.1709534e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.1830269e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.3766884e+01]]
-392.76993
[[ 9.1741707e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.1943672e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.3796471e+01]]
-392.7313
[[ 9.1786537e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.2041878e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.3829094e+01]]
-392.90536
[[ 9.1842728e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.785

-404.73468
[[ 9.5208801e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.4955162e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.5989754e+01]]
-403.53174
[[ 9.5244415e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.5027466e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.6060013e+01]]
-404.14886
[[ 9.5282364e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.5108002e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.6119057e+01]]
-405.86874
[[ 9.5322433e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.5186325e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.6178314e+01]]
-407.53305
[[ 9.5364426e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.5252922e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.6248016e+01]]
-409.0496
[[ 9.5398232e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.5308952e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  9.6337204e+01]]
-409.4302
[[ 9.5424660e+01 -7.4653560e-01 -6.3770908e-01]
 [-7.78

-430.48444
[[ 1.00484344e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  9.90674438e+01 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.01750214e+02]]
-430.72876
[[ 1.00523338e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  9.91302719e+01 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.01827255e+02]]
-429.14822
[[ 1.00574265e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  9.91829224e+01 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.01902634e+02]]
-429.4002
[[ 1.00635902e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  9.92264023e+01 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.01976524e+02]]
-427.66803
[[ 1.00697296e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  9.92714920e+01 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.02049049e+02]]
-425.89032
[[ 1.0074855e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  9.9327812e+01 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.0212033e+02]]
-424.2113
[[ 1.00800

[[ 1.0603988e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.0366310e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.0765946e+02]]
-449.74146
[[ 1.06092896e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.03760559e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.07684975e+02]]
-449.99265
[[ 1.0614651e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.0385426e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.0771388e+02]]
-450.24408
[[ 1.0620066e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.0394459e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.0774585e+02]]
-455.9192
[[ 1.0625535e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.0402203e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.0779079e+02]]
-452.92627
[[ 1.0630055e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.0409773e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.0784732e+02]]
-447.86044
[[ 1.0633721e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785

-479.14465
[[ 1.1208254e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.1132140e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.1405942e+02]]
-476.63052
[[ 1.12170975e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.11357231e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.14114418e+02]]
-479.76636
[[ 1.12266502e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.11385544e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.14169937e+02]]
-476.16104
[[ 1.12368324e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.11416946e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.14215698e+02]]
-476.4952
[[ 1.1247579e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.1145114e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.1425267e+02]]
-475.39166
[[ 1.12578476e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.11497643e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.14281731e+02]]
-475.66986
[[ 1.12676842e+02 

-495.36932
[[ 1.16778458e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.14659325e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.18170341e+02]]
-495.62238
[[ 1.16786705e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.14754410e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.18244781e+02]]
-490.91833
[[ 1.16800026e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.14855598e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.18307602e+02]]
-491.22577
[[ 1.16817917e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.14962257e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.18359955e+02]]
-494.1952
[[ 1.16849915e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.15064194e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.18402878e+02]]
-494.43173
[[ 1.1689458e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.1516187e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.1843732e+02]]
-494.69812
[[ 1.1695

-505.3916
[[ 1.18892700e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.19629181e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.21549515e+02]]
-509.4643
[[ 1.18972992e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.19688194e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.21588226e+02]]
-513.4689
[[ 1.19051369e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.19737404e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.21639221e+02]]
-517.41797
[[ 1.19117882e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.19777786e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.21711334e+02]]
-517.7257
[[ 1.1917371e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.1981022e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.2180231e+02]]
-514.3634
[[ 1.1923008e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.1983549e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.2190016e+02]]
-510.92303
[[ 1.1929694e+02 -7.46

-532.2861
[[ 1.2511687e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.2532343e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.2804877e+02]]
-532.848
[[ 1.2517197e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.2541019e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.2808243e+02]]
-536.9631
[[ 1.2522757e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.2549410e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.2811862e+02]]
-537.2133
[[ 1.25283623e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.25575455e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.28157089e+02]]
-541.1354
[[ 1.2534011e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.2564480e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.2820766e+02]]
-541.35974
[[ 1.25396996e+02 -7.46535599e-01 -6.37709081e-01]
 [-7.78565764e-01  1.25703331e+02 -7.32435584e-02]
 [-1.48699212e+00 -6.97048783e-01  1.28269089e+02]]
-542.05383
[[ 1.2544420e+02 -7.4653560e-01 -6.377090

 [-1.4869921e+00 -6.9704878e-01  1.3241165e+02]]
-561.71747
[[ 1.3113091e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3126379e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3250604e+02]]
-562.02747
[[ 1.3117607e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3129597e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3260701e+02]]
-562.36035
[[ 1.3121274e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3133080e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3271388e+02]]
-562.7136
[[ 1.3124174e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3136798e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3282603e+02]]
-565.1627
[[ 1.3126385e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3139752e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3295276e+02]]
-563.2967
[[ 1.3128970e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3142017e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3308269e+02]]
-561.3377
[[ 1.313

-584.71265
[[ 1.3688550e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3599176e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3952922e+02]]
-586.2396
[[ 1.3695924e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3602304e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3960078e+02]]
-586.55133
[[ 1.3704128e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3604726e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3967105e+02]]
-581.7377
[[ 1.3713068e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3607497e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3973019e+02]]
-585.7161
[[ 1.3721703e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3610585e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3978928e+02]]
-589.62244
[[ 1.3729082e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.3613963e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.3985828e+02]]
-589.86646
[[ 1.3735329e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785

-611.56995
[[ 1.4297057e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4231274e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.4600291e+02]]
-617.07477
[[ 1.4303157e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4234859e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.4608321e+02]]
-617.3899
[[ 1.4309242e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4237689e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.4617128e+02]]
-622.11957
[[ 1.4314323e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4239841e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.4627615e+02]]
-618.0971
[[ 1.4319492e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4241380e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.4638626e+02]]
-618.4834
[[ 1.4324739e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4242369e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.4650107e+02]]
-613.079
[[ 1.4330054e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.78565

-641.81067
[[ 1.4911879e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4809894e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5171771e+02]]
-645.79144
[[ 1.4917149e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4813913e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5180215e+02]]
-640.92346
[[ 1.4921498e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4818129e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5189398e+02]]
-637.4364
[[ 1.4926001e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4822522e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5198251e+02]]
-637.6886
[[ 1.4930643e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4827074e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5206807e+02]]
-639.4193
[[ 1.4936389e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.4830774e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5215097e+02]]
-638.19275
[[ 1.4942151e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785

 [-1.4869921e+00 -6.9704878e-01  1.5746939e+02]]
-657.3051
[[ 1.5527574e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5295830e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5749072e+02]]
-654.37634
[[ 1.5537579e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5301886e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5750574e+02]]
-651.34467
[[ 1.5546193e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5309903e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5751508e+02]]
-655.0414
[[ 1.5554523e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5318706e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5751929e+02]]
-661.5632
[[ 1.5562601e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5327232e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5752902e+02]]
-661.81384
[[ 1.5570451e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5335512e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.5754373e+02]]
-658.7169
[[ 1.557

-682.5471
[[ 1.5956528e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5879300e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6281967e+02]]
-682.7992
[[ 1.5964806e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5883687e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6287025e+02]]
-677.32886
[[ 1.5972845e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5889211e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6291162e+02]]
-678.79016
[[ 1.5981645e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5894775e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6294467e+02]]
-679.11975
[[ 1.5991129e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5900378e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6297025e+02]]
-685.1018
[[ 1.6001231e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.5905026e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6299921e+02]]
-685.431
[[ 1.6011890e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.78565

-705.9946
[[ 1.6503195e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6447362e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6815306e+02]]
-706.24817
[[ 1.6508257e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6452115e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6823331e+02]]
-710.9822
[[ 1.6512416e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6456992e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6832155e+02]]
-716.65576
[[ 1.6515762e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6460985e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6842696e+02]]
-711.65845
[[ 1.6518378e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6465178e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6853778e+02]]
-706.50433
[[ 1.6520334e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6470535e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.6864345e+02]]
-701.9302
[[ 1.6522684e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785

-719.7591
[[ 1.6967911e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6912128e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7397496e+02]]
-726.9475
[[ 1.6973721e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6920255e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7401277e+02]]
-727.9962
[[ 1.6979543e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6928171e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7405269e+02]]
-728.9824
[[ 1.6986351e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6934898e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7409450e+02]]
-729.2359
[[ 1.6994048e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6940556e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7413802e+02]]
-729.5171
[[ 1.7002541e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.6945250e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7418307e+02]]
-729.0052
[[ 1.7010774e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576

[[ 1.7533258e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.7520790e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7867133e+02]]
-751.31616
[[ 1.7541022e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.7528212e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7869501e+02]]
-756.2444
[[ 1.7548601e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.7534499e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7873236e+02]]
-761.0886
[[ 1.7555029e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.7539763e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7879202e+02]]
-756.5017
[[ 1.7560423e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.7545094e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7886166e+02]]
-756.77563
[[ 1.7564883e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.7550487e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.7894026e+02]]
-757.0757
[[ 1.7568504e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.

-785.38135
[[ 1.8131458e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8030258e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.8448837e+02]]
-779.6815
[[ 1.8132576e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8039395e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.8456194e+02]]
-775.42017
[[ 1.8134169e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8048209e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.8463403e+02]]
-775.6708
[[ 1.8136189e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8056731e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.8470480e+02]]
-775.92145
[[ 1.8138594e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8064990e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.8477438e+02]]
-775.1223
[[ 1.8140364e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8073984e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.8484290e+02]]
-775.4758
[[ 1.8141560e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856

[[ 1.8713101e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8527341e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9006061e+02]]
-798.44073
[[ 1.8719159e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8530757e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9014267e+02]]
-794.5082
[[ 1.8726161e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8534425e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9021242e+02]]
-792.03174
[[ 1.8733044e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8539301e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9027107e+02]]
-795.0246
[[ 1.8740788e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8544281e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9031973e+02]]
-795.31573
[[ 1.8749306e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8549358e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9035941e+02]]
-795.63007
[[ 1.8758517e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  

 [-1.4869921e+00 -6.9704878e-01  1.9234158e+02]]
-811.69226
[[ 1.9049670e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8912254e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9232710e+02]]
-816.5028
[[ 1.9057295e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8921721e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9233018e+02]]
-816.62036
[[ 1.9064745e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8929852e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9234908e+02]]
-812.4363
[[ 1.9072032e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8937759e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9237204e+02]]
-812.6854
[[ 1.9079175e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8945464e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9239867e+02]]
-812.93463
[[ 1.9086188e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.8952985e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9242860e+02]]
-813.1842
[[ 1.909

-832.56494
[[ 1.9484906e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9363800e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9813922e+02]]
-837.49255
[[ 1.9493935e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9368100e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9818236e+02]]
-839.47626
[[ 1.9502654e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9371574e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9823706e+02]]
-833.318
[[ 1.9511092e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9375298e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9829218e+02]]
-827.12585
[[ 1.9519272e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9380226e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9833766e+02]]
-825.4062
[[ 1.9526239e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9387209e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  1.9837448e+02]]
-825.7042
[[ 1.9532114e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856

 [-1.4869921e+00 -6.9704878e-01  2.0283516e+02]]
-855.5867
[[ 1.9999493e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9836285e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0291208e+02]]
-855.97815
[[ 2.0009975e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9835971e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0298721e+02]]
-860.49133
[[ 2.0020000e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9835291e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0307069e+02]]
-860.87146
[[ 2.0029614e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9834279e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0316167e+02]]
-865.35156
[[ 2.0037872e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9832971e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0326918e+02]]
-861.6905
[[ 2.0045897e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  1.9831396e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0338170e+02]]
-862.1245
[[ 2.00

-879.0823
[[ 2.0467244e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0345538e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0794583e+02]]
-874.70984
[[ 2.0473558e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0348785e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0802740e+02]]
-876.74207
[[ 2.0480817e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0351317e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0810672e+02]]
-877.0613
[[ 2.0488924e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0353203e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0818402e+02]]
-875.4652
[[ 2.0496811e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0355490e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0825948e+02]]
-880.39526
[[ 2.0503514e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0358141e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.0834325e+02]]
-880.6708
[[ 2.0509149e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856

 [-1.4869921e+00 -6.9704878e-01  2.1369148e+02]]
-904.89886
[[ 2.0994691e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0907826e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1377953e+02]]
-910.6681
[[ 2.0997662e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0912056e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1388438e+02]]
-905.54236
[[ 2.1000932e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0915469e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1399448e+02]]
-900.23206
[[ 2.1005453e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0918149e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1409943e+02]]
-894.76996
[[ 2.1012067e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0920166e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1418980e+02]]
-893.7441
[[ 2.1019583e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.0922571e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1426707e+02]]
-892.6118
[[ 2.10

-916.8152
[[ 2.1400481e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1355415e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1828966e+02]]
-923.80493
[[ 2.1404628e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1364565e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1833305e+02]]
-930.1023
[[ 2.1407961e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1372408e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1839783e+02]]
-930.3788
[[ 2.1410559e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1379073e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1848170e+02]]
-924.494
[[ 2.1413498e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1384679e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1857288e+02]]
-918.0699
[[ 2.1416742e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1390317e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.1866075e+02]]
-911.94763
[[ 2.1421249e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785657

-944.3324
[[ 2.1942999e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1873111e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2325792e+02]]
-938.22327
[[ 2.1945270e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1880310e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2334048e+02]]
-938.54553
[[ 2.1946912e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1888367e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2342065e+02]]
-945.34357
[[ 2.1947986e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1896216e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2350858e+02]]
-946.4457
[[ 2.1949554e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1902885e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2360345e+02]]
-940.2274
[[ 2.1951566e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.1909483e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2369470e+02]]
-934.55066
[[ 2.1954968e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785

-958.5989
[[ 2.2183260e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2354192e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2667743e+02]]
-961.2466
[[ 2.2188641e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2361433e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2672894e+02]]
-961.4963
[[ 2.2193082e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2368542e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2679120e+02]]
-961.77466
[[ 2.2196675e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2375533e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2686311e+02]]
-959.5219
[[ 2.2200519e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2381427e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2694366e+02]]
-959.8054
[[ 2.2204588e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2386336e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.2703198e+02]]
-953.0206
[[ 2.2209865e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785657

-969.5786
[[ 2.2735500e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2833986e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3255472e+02]]
-970.0078
[[ 2.2748491e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2838919e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3255363e+02]]
-977.6411
[[ 2.2760789e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2843956e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3255855e+02]]
-979.08203
[[ 2.2771460e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2850076e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3256885e+02]]
-979.2712
[[ 2.2780664e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2857170e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3258401e+02]]
-972.71155
[[ 2.2789551e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.2865132e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3259352e+02]]
-973.06433
[[ 2.2798152e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856

-990.79504
[[ 2.3228271e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3191393e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3401692e+02]]
-988.06476
[[ 2.3233337e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3199712e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3406065e+02]]
-988.8982
[[ 2.3238489e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3208771e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3409589e+02]]
-989.22925
[[ 2.3243716e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3218492e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3412346e+02]]
-989.5802
[[ 2.3249014e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3228810e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3414415e+02]]
-992.29944
[[ 2.3253381e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3239664e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.3416878e+02]]
-995.1647
[[ 2.3256911e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.785

-1014.45667
[[ 2.3733560e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3693195e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4062811e+02]]
-1014.72876
[[ 2.3737976e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3700847e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4068457e+02]]
-1015.027
[[ 2.3741548e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3709306e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4074126e+02]]
-1015.3484
[[ 2.3744362e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3718491e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4079817e+02]]
-1015.6909
[[ 2.3746492e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3728325e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4085529e+02]]
-1021.1341
[[ 2.3748007e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.3737770e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4092255e+02]]
-1016.41675
[[ 2.3748969e+02 -7.4653560e-01 -6.3770908e-01]
 [-

[[ 2.4306400e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4257559e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4852049e+02]]
-1034.9578
[[ 2.4318901e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4260466e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4854187e+02]]
-1042.9451
[[ 2.4330745e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4263680e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4856688e+02]]
-1042.2382
[[ 2.4341013e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4268164e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4859517e+02]]
-1042.4062
[[ 2.4349861e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4273790e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4862640e+02]]
-1035.3428
[[ 2.4358414e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4280434e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.4865044e+02]]
-1036.763
[[ 2.4367671e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01 

-1072.9076
[[ 2.4944606e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4875844e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5341089e+02]]
-1073.1774
[[ 2.4948318e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4883005e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5347913e+02]]
-1073.4735
[[ 2.4951263e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4890051e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5355624e+02]]
-1073.7931
[[ 2.4953517e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4896996e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5364133e+02]]
-1074.9418
[[ 2.4956139e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4902846e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5373357e+02]]
-1068.5454
[[ 2.4959088e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.4908711e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5382242e+02]]
-1068.7969
[[ 2.4962334e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.

-1090.6796
[[ 2.5449345e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.5412114e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5944763e+02]]
-1083.3735
[[ 2.5454036e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.5420636e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5949258e+02]]
-1084.158
[[ 2.5459824e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.5428905e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5952896e+02]]
[[ 2.5459824e+02 -7.4653560e-01 -6.3770908e-01]
 [-7.7856576e-01  2.5428905e+02 -7.3243558e-02]
 [-1.4869921e+00 -6.9704878e-01  2.5952896e+02]]
