In [1]:
# Imports

import math
import numpy as np
from matplotlib import pyplot as plt
from numpy import random as rnd
import warnings,datetime,os,calendar,csv,time

import tensorflow as tf
import pandas as pd
import seaborn as sns

from keras.models import Model,Sequential
from keras.layers import Dense,LSTM,Conv2D,Dropout,BatchNormalization,Input,Concatenate,Add,Activation,MaxPooling2D,AveragePooling2D
import keras.backend as K

from sklearn import preprocessing as pp

from sklearn.cluster import KMeans,MeanShift
from sklearn.dummy import DummyClassifier,DummyRegressor
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,RandomForestClassifier,RandomForestRegressor
from sklearn.linear_model import BayesianRidge,Lasso,LinearRegression,SGDClassifier,SGDRegressor
from sklearn.mixture import BayesianGaussianMixture,GaussianMixture
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor,RadiusNeighborsClassifier,RadiusNeighborsRegressor,NearestNeighbors
from sklearn.manifold import Isomap,TSNE
from sklearn.model_selection import KFold,StratifiedKFold,train_test_split
from sklearn.svm import LinearSVC,LinearSVR
from sklearn.neural_network import BernoulliRBM,MLPClassifier,MLPRegressor
from sklearn.decomposition import FactorAnalysis,KernelPCA,PCA,MiniBatchSparsePCA,FastICA
from sklearn.preprocessing import CategoricalEncoder,KBinsDiscretizer,LabelEncoder,MinMaxScaler,OneHotEncoder,StandardScaler

from xgboost import XGBClassifier,XGBRegressor

import pickle,h5py,json

warnings.filterwarnings('ignore')
sns.set()

C:\Users\Jan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [53]:
N = 3

num_samples = 10**6

In [54]:
in0 = Input(shape=(N,))
x = Dense(units=1000,activation='linear')(in0)
out0 = Dense(units=N,activation='linear')(x)

model = Model(in0,out0)
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [55]:
X = []
Y = []

for k in range(num_samples):
    
    x = rnd.randn(N)
    y = x*(x>0)
    
    X.append(x)
    Y.append(y)
    
X = np.stack(X,axis=0)
Y = np.stack(Y,axis=0)

In [56]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2,shuffle=True)

In [57]:
model.fit(Xtrain,Ytrain,batch_size=10,epochs=5,validation_split=0.1)

Train on 720000 samples, validate on 80000 samples
Epoch 1/5
720000/720000 [==============================] - 122s 169us/step - loss: 0.0928 - acc: 0.8935 - val_loss: 0.0912 - val_acc: 0.8993
Epoch 2/5
720000/720000 [==============================] - 119s 165us/step - loss: 0.0919 - acc: 0.8994 - val_loss: 0.0911 - val_acc: 0.9092
Epoch 3/5
720000/720000 [==============================] - 123s 171us/step - loss: 0.0917 - acc: 0.9010 - val_loss: 0.0923 - val_acc: 0.8924
Epoch 4/5
720000/720000 [==============================] - 135s 188us/step - loss: 0.0917 - acc: 0.9019 - val_loss: 0.0931 - val_acc: 0.9042
Epoch 5/5
720000/720000 [==============================] - 119s 166us/step - loss: 0.0917 - acc: 0.9019 - val_loss: 0.0921 - val_acc: 0.9061


In [58]:
model.evaluate(Xtest,Ytest)

200000/200000 [==============================] - 4s 19us/step


[0.09246604783296584, 0.90449]

In [59]:
Xtest[0,:]

array([-1.38011357,  1.88087616,  0.11922288])

In [60]:
model.predict(Xtest[0,:].reshape(-1,3))

array([[-0.30759132,  1.363164  ,  0.44330162]], dtype=float32)

In [48]:
Xtest[0,:]

array([ 0.55556975, -0.34805626, -0.04802922])